### ISSUE TITLE
VCG Bug

### ISSUE THREAD

**Issue by TeToNN** [NamTThai/PokemonShowdownAndroidClient#67]
User can't start a battle (need to select 4 pokemons out of the 6)

Message is |teampreview|4

Expects output like battle-vgc2015-199947848|/team 6543|1 (if the user picked pokemon 6/5/4/3 in that order)

**Comment by Lazloz** [comment]
Does this also affect Zoroark? You have to select your team order if you are using him.

**Comment by jake-white** [comment]
Any progress on this bug? Really hyped to try out the app but unfortunately I only play VGC.

**Comment by NamTThai** [comment]
@jake-white hey Jake, thanks for stopping by. Currently I have banging my head against a recently found bug that freezes apps. This bug takes quite a while to fix. So realisticly, I can get to VGC during mid-February.

**Comment by jake-white** [comment]
Alright, thanks for the response.  I am very much looking forward to it!

**Comment by NamTThai** [comment]
Resolved as of 1.1
