### ISSUE TITLE
Mega-Evolution-Bug

### ISSUE THREAD

**Issue by DManstrator** [NamTThai/PokemonShowdownAndroidClient#77]
Sry, don't want to register in the forum so I'm telling it you here.

After mega-evolving Mawile and switching it out, it can't be send to battle, again. In addition too, I got an error during selecting a move. After fake-switching into another pokemon, the pokemon will attack, but some time later (e.g. if there is only Mega-Mawile and an other pokemon left), I can't do anything except forfeiting. Maybe it's due to this pokemon, I can send the code of the team if required. 

Here a screenshot of the error: http://puu.sh/fkc6T/b5ee00f840.png

Hope you could fix it. :]

Kind Regards, DMan

**Comment by NamTThai** [comment]
Thanks, @DManstrator! I'll look into it

**Comment by NamTThai** [comment]
Resolved as of 1.1
